core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurant/',include('reastaurant.urls')),
    path('',include("user.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "user.views.page404"

reastaurant/urls.py
from django.urls import path
from . import views
app_name = 'reastaurent'
urlpatterns = [
    path('/<id>/',views.restaurant,name='restaurant'),
    path('all/',views.restaurants,name="restaurant_all"),
    path('cart/',views.cart, name='cart'),
    path('add_to_cart/<res_id>/<food_id>/',views.add_to_cart,name="add_to_cart"),
    path('increment_quantity/<cart_id>/',views.increment_quantity,name="increment_quantity"),
    path('decrement_quantity/<cart_id>/',views.decrement_quantity,name="decrement_quantity"),
    path('delete_all_cart/',views.delete_all_cart,name="delete_all_cart"),
    path('delete_cart/',views.delete_cart,name="delete_cart"),
    path('food/<id>/',views.food,name='food'),
    path('view_all_food',views.view_all_food,name='view_all_food'),
    path('shipping',views.shipping,name="shipping"),
    path('search',views.search,name='search'),
]

user/urls.py
from django.urls import path
from . import views


app_name= 'user'
urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.custom_login,name='login'),
    path('signup/',views.signup,name='signup'),   
    path('logout/',views.custom_logout,name='logout'),   
    path('profile_update/',views.profile_update,name='profile_update'),
    path('profile/',views.profile,name='profile'),
    path('update_session/',views.update_session,name='update_session'),
]



    

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    def create_superuser(self,email, password, **extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_active',True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True'))
        return self.create_user(email,password,**extra_fields)


class Address(models.Model):
    latitude = models.DecimalField(max_digits=9,decimal_places=6, null=True)
    longitude = models.DecimalField(max_digits=9,decimal_places=9, null=True)
    area = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=50,null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    pincode = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.area

class users(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    address = models.OneToOneField(Address, blank=True,null=True, on_delete=models.SET_NULL, related_name="user_address")
    image = models.ImageField(null=True, blank=True,default="default.png")
    phone = models.CharField(max_length=50,null=True,blank=True)
    is_customer = models.BooleanField(default=True)
    is_delivery_person = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

user/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from django.contrib.auth import authenticate, login, logout
from reastaurant.models import Restaurant, Image, Food
from .models import users, Address
import logging
from django.views.decorators.csrf import csrf_exempt
import json
from reastaurant.models import Image
from django.contrib.auth.decorators import login_required
from geopy.geocoders import Nominatim



def home(request):
    # print(request.session.get('latitude',None))
    restaurents = Restaurant.objects.all()[:10]
    foods = Food.objects.all()[:10]
    return render(request, "index.html",context= {"restaurants": restaurents, "foods":foods})

def custom_login(request):
    if request.method == 'POST':
        try:
            data = request.POST.dict()
            email=data.get('email')
            password=data.get('password')
            user = authenticate(request,email=email, password=password)
            if user is not None:
                login(request, user)
                print('login successfull')
                print(request.user.username)
                return redirect('/')
            else:
                return render(request,'login.html',{
                        'error':True
                })
        except Exception as ex:
            logging.warning(ex)
            return render(request,'error.html')

    return render(request,'login.html',{
        'error':False,
    })
def signup(request):
    if request.method == 'POST':
        try:
            data = request.POST.dict()
            email=data.get('email')
            password=data.get('password')
            cpassword=data.get('cpassword')
            print(password)
            print(cpassword)
            if password != cpassword:
                return render(request,'signup.html',{"same_password":True} )
            user = users.objects.create_user(email=email, password=password)
            return redirect(reverse('user:login'))
        except Exception as ex :
            print('Exception occured')
            print(ex)
            return render(request, 'signup.html',{
                'error':True
            })

    return render(request, 'signup.html',{
        'error':False,
        "same_password":False
    })

@login_required(login_url='user:login')
def custom_logout(request):
    logout(request)
    print('logout successfully')
    return redirect('/')

@login_required(login_url='user:login')
def profile_update(request):
    if request.method == 'POST':
        try:
            data = request.POST.dict()
            print(data)
            file = request.FILES.get('file')
            user = users.objects.get(id=request.user.id)
            user.first_name=data['first_name']
            user.last_name=data['last_name']
            user.phone = data['phone']
            if file is not None:
                user.image = file
            if user.address == None:
                print('address is not available')
                address = Address(area=data['area'],city=data['city'],state=data['state'],country=data['country'], pincode=data['pincode'])
                address.save()
                user.address = address
            else:
                user.address.area = data['area']
                user.address.city = data['city']
                user.address.state = data['state']
                user.address.country = data['country']
                user.address.pincode = data['pincode']
                user.address.save()
            user.save()
            return HttpResponse('success!!')
        except Exception as ex:
            logging.warning(ex)
            return render(request,'error.html')
    return render(request,'profile_update.html')

@login_required(login_url='user:login')
def profile(request):
    return render(request,'profile.html')

def page404(request, exception):
    return render(request,'page404.html')

def update_session(request):
    data = request.POST.dict()
    print(data)
    request.session['latitude'] = data['latitude']
    request.session['longitude'] = data['longitude']

    geolocator = Nominatim(user_agent="kundan")
    latitude = request.session.get('latitude',None)
    longitude = request.session.get('longitude',None)
    location = geolocator.reverse(latitude+","+longitude)
    address = location.raw['address']
    city = None
    state = None
    restaurants = None
    foods = None
    if 'city' not in address.keys() and 'state' not in address.keys():
        restaurants = Restaurant.objects.all().order_by('id')
    elif 'city' not in address.keys():
        state = address['state']
        print('restaurant all')
        add = Address.objects.filter(state__iexact=state).values_list('id')
        restaurants = Restaurant.objects.filter(address__id__in=add).order_by('id')
    elif 'state' not in address.keys():
        city = address['city']
        print('restaurant all')
        add = Address.objects.filter(city__iexact=city).values_list('id')
        restaurants = Restaurant.objects.filter(address__id__in=add).order_by('id')
    else:
        city = address['city']
        state = address['state']
        print('restaurant all')
        add = Address.objects.filter(city__iexact=city,state__iexact=state).values_list('id')
        restaurants = Restaurant.objects.filter(address__id__in=add).order_by('id')
        foods = Food.objects.filter(restaurants_foods__id__in = restaurants.values_list('id'))[:10]        
    return render(request, "content.html",context= {"restaurants": restaurants, "foods":foods})

user/templates/content.html
<br><br>
<div class="restureant">
  <a href="{% url 'reastaurent:restaurant_all' %}" class="text-decoration-none"><h3>Restaurants</h3></a>
    <div class="scrollmenu">
        {% if reastaurants|length > 1 %}
      {% for restaurant in restaurants  %}
      <div class="card">
        <a href="{% url 'reastaurent:restaurant' restaurant.id %}">
          <img class="card-im card-img-top" src="{{restaurant.image.all.0.image.url}}" alt="Card image cap">
        </a>
        <div class="card-body">
          <h5 class="card-title">{{restaurant.name}} <span>{{restaurant.rating}} <i class="fa-solid fa-star"></i></span></h5>
          
          
          <p class="card-text">Address : {{restaurant.address.area}},{{restaurant.address.city}}</p>  
        </div>
      </div>
      {% endfor %} 
      {% else %}
      <h5>Sorry!! No Reastoreant is available at your area</h5>
      {% endif %}
    </div> 
</div>

<br><br>
<div class="deliciousfood">
  <a href="{% url 'reastaurent:view_all_food' %}" class="text-decoration-none"><h3>Delicious Food</h3></a>
    <div class="scrollmenu">
        {% if foods|length > 1 %}
      {% for food in foods  %}
      <div class="card">
        <a href="{% url 'reastaurent:food' food.id %}">
          <img class="card-im card-img-top" src="{{food.image.all.0.image.url}}" alt="Card image cap">
        </a>
        <div class="card-body">
          <h5 class="card-title">{{food.name}} <span><i class="fa-solid fa-indian-rupee-sign"></i> {{food.price}}</span></h5>
        </div>
      </div>
      {% endfor %} 
      {% else %}
        <h5>Sorry!! No food are available at your area!!</h5>
      {% endif %}
    </div>
</div>

user/templates/index.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}

    <!-- Reastoreant -->
    

    <div class="slidebar">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100 h-20" src="{% static '/img/slider4.jpg' %}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
              <h5> Delicious Food </h5>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, reprehenderit?</p>
              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias ut, laborum minus quaerat magnam rerum porro hic veniam in ab?</p>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100 h-20" src="{% static '/img/slider1.jpg' %}" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
              <h5> Delicious Food </h5>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, reprehenderit?</p>
              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias ut, laborum minus quaerat magnam rerum porro hic veniam in ab?</p>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100 h-20" src="{% static '/img/slider2.jpg' %}" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
              <h5> Delicious Food </h5>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, reprehenderit?</p>
              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias ut, laborum minus quaerat magnam rerum porro hic veniam in ab?</p>
            </div>
          </div>
        </div>

        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div class="content" id = 'content'>
    
    <br><br>
    <div class="restureant">
      <a href="{% url 'reastaurent:restaurant_all' %}" class="text-decoration-none"><h3>Restaurants</h3></a>
        <div class="scrollmenu">
          {% if reastaurants|length > 1 %}

          {% for restaurant in restaurants  %}
          <div class="card">
            <a href="{% url 'reastaurent:restaurant' restaurant.id %}">
              <img class="card-im card-img-top" src="{{restaurant.image.all.0.image.url}}" alt="Card image cap">
            </a>
            <div class="card-body">
              <h5 class="card-title">{{restaurant.name}} <span>{{restaurant.rating}} <i class="fa-solid fa-star"></i></span></h5>
              
              
              <p class="card-text">Address : {{restaurant.address.area}},{{restaurant.address.city}}</p>  
            </div>
          </div>
          {% endfor %} 
          {% else %}
          <h2>Sorry!! No Reastoreant is available at your area</h2>
          {% endif %}
        </div> 
    </div>




    <br><br>
    <div class="deliciousfood">
      <a href="{% url 'reastaurent:view_all_food' %}" class="text-decoration-none"><h3>Delicious Food</h3></a>
        <div class="scrollmenu">
          {% if foods|length > 1 %}
          {% for food in foods  %}
          <div class="card">
            <a href="{% url 'reastaurent:food' food.id %}">
              <img class="card-im card-img-top" src="{{food.image.all.0.image.url}}" alt="Card image cap">
            </a>
            <div class="card-body">
              <h5 class="card-title">{{food.name}} <span><i class="fa-solid fa-indian-rupee-sign"></i> {{food.price}}</span></h5>
            </div>
          </div>
          {% endfor %} 
          {% else %}
          <h5>Sorry !! No food is available at your area!!</h5>
          {% endif %}
        </div>
    </div>

  </div>

    {% endblock content %}

    {% block javascript %}
    <script type="application/javascript" >
      const successCallback = (position) => {
          let data = new FormData();
          data.append("csrfmiddlewaretoken", "{{csrf_token}}");
          data.append('latitude', position.coords.latitude);
          data.append('longitude', position.coords.longitude);
            $.ajax({
              type: 'POST',
              url: {% url 'user:update_session' %},
              success: function(e) { 
                document.getElementById('content').innerHTML = e;
              },
              processData:false,
              contentType:false,
              data:data
            });
        }
        const errorCallback = (error) => {
        console.log(error);
        };
      navigator.geolocation.getCurrentPosition(successCallback, errorCallback,{maximumAge:60000, timeout:5000, enableHighAccuracy:true});
    </script>

    {% endblock javascript %}

user/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href=" {% static 'css/login.css' %} ">
</head>
<body>

    <div class="login-page">
        <div class="form">
          <form class="login-form" method='POST'>
            {% csrf_token %}
            {% if error == True %}
              <p style="color:red";>Password or Username are invalid!!</p>
            {% endif %}
            <input type="email" name='email' placeholder="email"/>
            <input type="password" name='password' placeholder="password"/>
            
            <button type = 'submit'>login</button>
            <p class="message">Not registered? <a href=" {% url 'user:signup' %}">Create an account</a></p>
          </form>
        </div>
      </div>
      
</body>
</html>

user/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/profile_update.css' %}">
{% endblock extra_css %}

{% block content %}
<div class="container">
    <div class="row gutters">
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="account-settings">
                <div class="user-profile">
                    <div class="user-avatar">
                        <img src="{{request.user.image.url}} " alt="{{request.user.first_name}}">
                    </div>
                    <h5 class="user-name">{{request.user.first_name}}</h5>
				    <h6 class="user-email">{{request.user.email}}</h6>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mb-2 text-primary">Personal Details</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    
                    <div class="form-group">
                        <p>Name : {{request.user.first_name}} {{request.user.last_name}}</p>
                    </div>
                    <div class="form-group">
                        <p>Phone : {{request.user.phone}} </p>
                    </div>
                    <div class="form-group">
                        <p>Email : {{request.user.email}} </p>
                    </div>
                </div>
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mt-3 mb-2 text-primary">Address</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <p>{{request.user.address.area}}</p>
                    <p>Zip Code : {{request.user.address.pincode}}</p>
                    <p>City : {{request.user.address.city}}</p>
                    <p>State : {{request.user.address.state}}</p>
                    <p>Country: {{request.user.address.country}}</p>
                    
                </div>
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                        <a href="{% url 'user:profile_update' %}" id="submit" name="submit" class="btn btn-primary">Update</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    {% endblock content %}

    

user/templates/profile_update.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/profile_update.css' %}">
{% endblock extra_css %}

{% block content %}

<div class="container">
    <div class="row gutters">
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="account-settings">
                <div class="user-profile">
                    <div class="user-avatar">
                        <img src="{{request.user.image.url}}" alt="{{request.user.first_name}}">
                    </div>
                    <h5>Upload new image</h5>
                    <input type="file" id="upload_image" class="btn btn-primary" style="max-width:230px";>                    
                </div>
                
            </div>
        </div>
    </div>
    </div>
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mb-2 text-primary">Personal Details</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" class="form-control" id="first_name" placeholder="Enter First name" value="{{request.user.first_name}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" class="form-control" id="last_name" placeholder="Enter Last name" value="{{request.user.last_name}}">
                    </div>
                </div>
                
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" class="form-control" id="phone" placeholder="Enter phone number" value="{{request.user.phone}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="eMail">Email</label>
                        <input type="email"  class="form-control" id="eMail" placeholder="Enter email ID" value="{{request.user.email}}" disabled>
                    </div>
                </div>
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mt-3 mb-2 text-primary">Address</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="Street">Area</label>
                        <input type="name" class="form-control" id="area" placeholder="Enter Area" value="{{request.user.address.area}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="ciTy">City</label>
                        <input type="name" class="form-control" id="ciTy" placeholder="Enter City" value="{{request.user.address.city}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="sTate">State</label>
                        <input type="text" class="form-control" id="sTate" placeholder="Enter State" value="{{request.user.address.state}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="zIp">Zip Code</label>
                        <input type="text" class="form-control" id="zIp" placeholder="Zip Code" value="{{request.user.address.pincode}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="country">Country</label>
                        <input type="text" class="form-control" id="country" placeholder="Enter Country" value="{{request.user.address.country}}">
                    </div>
                </div>
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                        <a href="{% url 'user:profile' %}" id="submit" name="submit" class="btn btn-secondary">Cancel</a>
                        <input type="button" id="submit" name="submit" class="btn btn-primary" onclick="update_profile()" value="Save" >
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>

    {% endblock content %}

    {% block javascript %}
        <script type="text/javascript">
            let first_name,last_name,phone,area,city,state,pincode,country
            function update_profile(){
                first_name=$("#first_name").val();
                last_name=$("#last_name").val();
                phone = $("#phone").val();
                area = $("#area").val();
                city = $("#ciTy").val();
                state = $("#sTate").val();
                country = $("#country").val();
                pincode = $("#zIp").val();
                let data = new FormData();
                data.append("file",$("input[id^='upload_image']")[0].files[0]);
                data.append("csrfmiddlewaretoken", "{{csrf_token}}");
                data.append("first_name",first_name);
                data.append("last_name",last_name);
                data.append("phone",phone);
                data.append("area",area);
                data.append("city",city);
                data.append("state",state);
                data.append("country",country);
                data.append("pincode",pincode);
                $.ajax({
                    type: 'POST',
                    url: {% url 'user:profile_update' %},
                    success: function(e) { window.location='{% url 'user:profile' %}' },
                    processData:false,
                    contentType:false,
                    data:data
                });
            }
        </script>
    {% endblock javascript %}

user/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static 'css/login.css' %} ">
    <title>Document</title>
</head>
<body>
    
    <div class="login-page">
        <div class="form">
          <form class="register-form" method='POST'>
            {% csrf_token %}
            {% if error == True %}
              <p style="color:red";>Email is already taken!!!</p>
            {% endif %}
            <input type="email" name='email' placeholder='email'>
            <input type="password" name='password' placeholder="password"/>
            <input type="password" name='cpassword' placeholder="confirm password"/>

            {% if same_password == True %}
              <p style="color:red";>Password and confirm password do not match!!1</p>
            {% endif %}

            <button type = 'submit' onclick="validateUser()">create</button>
            <p class="message">Already registered? <a href=" {% url 'user:login' %} ">Sign In</a></p>
          </form>
        </div>
      </div>
</body>
</html>