core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurant/',include('reastaurant.urls')),
    path('',include("user.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "user.views.page404"

reastaurant/urls.py
from django.urls import path
from . import views
app_name = 'reastaurent'
urlpatterns = [
    path('/<id>/',views.restaurant,name='restaurant'),
    path('all/',views.restaurants,name="restaurant_all"),
    path('cart/',views.cart, name='cart'),
    path('add_to_cart/<res_id>/<food_id>/',views.add_to_cart,name="add_to_cart"),
    path('increment_quantity/<cart_id>/',views.increment_quantity,name="increment_quantity"),
    path('decrement_quantity/<cart_id>/',views.decrement_quantity,name="decrement_quantity"),
    path('delete_all_cart/',views.delete_all_cart,name="delete_all_cart"),
    path('delete_cart/',views.delete_cart,name="delete_cart"),
    path('food/<id>/',views.food,name='food'),
    path('view_all_food',views.view_all_food,name='view_all_food'),
    path('shipping',views.shipping,name="shipping"),
    path('search',views.search,name='search'),
]

user/urls.py
from django.urls import path
from . import views


app_name= 'user'
urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.custom_login,name='login'),
    path('signup/',views.signup,name='signup'),   
    path('logout/',views.custom_logout,name='logout'),   
    path('profile_update/',views.profile_update,name='profile_update'),
    path('profile/',views.profile,name='profile'),
    path('update_session/',views.update_session,name='update_session'),
]



    

templates/include/footer.html
<br>
<footer class="page-footer font-small bg-light">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2022 Copyright:
      <a href="#"> Kundan Kumar Gupta</a>
    </div>
    <!-- Copyright -->
  
  </footer>

templates/include/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <a class="navbar-brand" href="{% url 'user:home' %}">Food Delivery</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reastaurent:restaurant_all' %}">Restaurant</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reastaurent:view_all_food' %}">Food</a>
        </li>
        {% comment %} <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Food Category
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Veg Only</a>
            <a class="dropdown-item" href="#">Non Veg</a>
            <a class="dropdown-item" href="{% url 'reastaurent:view_all_food' %}">Both Veg & non Veg</a>
          </div>
        </li> {% endcomment %}
        {% if  request.user.is_authenticated %}
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'reastaurent:cart' %}" class="nav-link">{{request.user.all_cart_food.all.count}} <i class="fas fa-shopping-cart"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:profile' %}">Hi, {{request.user.first_name}}</a>
          </li>
          <li class="nav-item dropdown nav-user" style="margin-right:20px;">
            <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{request.user.image.url}}" alt="" height="25" class="user-avatar-md rounded-circle"></a>
            <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                <a class="dropdown-item" href="{% url 'user:profile' %}"><i class="fas fa-user mr-2"></i>Profile</a>
                <a class="dropdown-item" href="{% url 'user:logout' %}" ><i class="fas fa-power-off mr-2"></i>Logout</a>
            </div>
          </li>
        </ul>


        {% else %}
          <li class="nav-item mr-auto" >
            <a class="nav-link" href="{% url 'user:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
          </li>
         </ul>
        {% endif %}

        

    </div>

    <form class="form-inline my-2 my-lg-0" action="{% url 'reastaurent:search' %}" method='POST'>
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </nav>