core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurant/',include('reastaurant.urls')),
    path('',include("user.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "user.views.page404"

reastaurant/urls.py
from django.urls import path
from . import views
app_name = 'reastaurent'
urlpatterns = [
    path('/<id>/',views.restaurant,name='restaurant'),
    path('all/',views.restaurants,name="restaurant_all"),
    path('cart/',views.cart, name='cart'),
    path('add_to_cart/<res_id>/<food_id>/',views.add_to_cart,name="add_to_cart"),
    path('increment_quantity/<cart_id>/',views.increment_quantity,name="increment_quantity"),
    path('decrement_quantity/<cart_id>/',views.decrement_quantity,name="decrement_quantity"),
    path('delete_all_cart/',views.delete_all_cart,name="delete_all_cart"),
    path('delete_cart/',views.delete_cart,name="delete_cart"),
    path('food/<id>/',views.food,name='food'),
    path('view_all_food',views.view_all_food,name='view_all_food'),
    path('shipping',views.shipping,name="shipping"),
    path('search',views.search,name='search'),
]

user/urls.py
from django.urls import path
from . import views


app_name= 'user'
urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.custom_login,name='login'),
    path('signup/',views.signup,name='signup'),   
    path('logout/',views.custom_logout,name='logout'),   
    path('profile_update/',views.profile_update,name='profile_update'),
    path('profile/',views.profile,name='profile'),
    path('update_session/',views.update_session,name='update_session'),
]



    

reastaurant/models.py
from django.db import models
from user.models import Address
from user.models import users
class Category(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Image(models.Model):
    image = models.ImageField(upload_to="img")
    def __str__(self):
        return self.image.name

class Item(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='food_categories')

    def __str__(self):
        return self.name


class Food(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    image = models.ManyToManyField(Image)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='food_items')
    
    def __str__(self):
        return self.name

class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    image = models.ManyToManyField(Image, related_name="restaurant_image_name")
    address = models.OneToOneField(Address, null=True, blank=True, on_delete=models.SET_NULL, related_name="restaurant_address")
    phone = models.CharField(max_length=10,blank=True)
    food = models.ManyToManyField(Food,related_name="restaurants_foods")
    rating = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    food = models.ForeignKey(Food, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    user = models.ForeignKey(users, on_delete=models.CASCADE, null=True,blank=True, related_name="all_cart_food")
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, null=True, blank=True)

class Order(models.Model):
    price = models.IntegerField(default=0)
    user = models.ForeignKey(users, on_delete=models.CASCADE, related_name="all_order_user")
    payment = models.CharField(max_length=20)

reastaurant/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from .models import Restaurant, Image, Food, Cart, Order
from user.models import users
import logging
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from geopy.geocoders import Nominatim
from user.models import Address
import geopy.distance


def restaurant(request, id):
    try:
        restaurent = Restaurant.objects.get(id=id)
        return render(request, "restaurant.html",context= {"restaurant": restaurent, "foods":""})
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')

def restaurants(request):
    try:
        geolocator = Nominatim(user_agent="kundan")
        latitude = request.session.get('latitude',None)
        longitude = request.session.get('longitude',None)
        restaurants = None
        if latitude == None or longitude == None:
            restaurants = Restaurant.objects.all().order_by('id')
        else:
            print(latitude)
            print(longitude)
            location = geolocator.reverse(latitude+","+longitude)
            address = location.raw['address']
            city = None
            state = None
            if 'city' not in address.keys() and 'state' not in address.keys():
                restaurants = Restaurant.objects.all().order_by('id')
            elif 'city' not in address.keys():
                state = address['state']
                print('restaurant all')
                add = Address.objects.filter(state__iexact=state).values_list('id')
                restaurants = Restaurant.objects.filter(address__id__in=add).order_by('id')
            elif 'state' not in address.keys():
                city = address['city']
                print('restaurant all')
                add = Address.objects.filter(city__iexact=city).values_list('id')
                restaurants = Restaurant.objects.filter(address__id__in=add).order_by('id')
            else:
                city = address['city']
                state = address['state']
                print(city)
                print(state)
                print('restaurant all')
                add = Address.objects.filter(city__iexact=city,state__iexact=state).values_list('id')
                restaurants = Restaurant.objects.filter(address__id__in=add).order_by('id')
        paginator = Paginator(restaurants, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request,'restaurants.html',context={"page_obj":page_obj})
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')

@login_required(login_url='user:login')
def cart(request):
    try:
        carts = request.user.all_cart_food.all()
        total=0
        for cart in carts:
            total += cart.quantity * cart.food.price
        return render(request, "cart.html", context={"carts":carts,"total_price":total})
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')

@login_required(login_url='user:login')
def add_to_cart(request, res_id, food_id):
    try:
        carts = request.user.all_cart_food.all()
        if(len(carts)==0):
            restaurant = Restaurant.objects.get(id=res_id)
            food = Food.objects.get(id=food_id)
            cart = Cart(food=food, quantity = 1,user=request.user, restaurant = restaurant)
            cart.save()
        else:
            res = carts[0].restaurant.id
            if int(res) != int(res_id):
                carts = request.user.all_cart_food.all()
                total=0
                for cart in carts:
                    total += cart.quantity * cart.food.price
                return render(request, "cart.html", context={"carts":carts,"total_price":total,"cart_is_full":True})
            else:
                for cart in carts:
                    if int(cart.food.id) == int(food_id):
                        cart.quantity = cart.quantity+1
                        cart.save()
                        return redirect(reverse('reastaurent:cart'))
                food = Food.objects.get(id=food_id)
                cart = Cart(food=food,quantity=1,user = request.user, restaurant =carts[0].restaurant)
                cart.save()
                print(cart)
        return redirect(reverse('reastaurent:cart'))
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')


@login_required(login_url='user:login')
def decrement_quantity(request,cart_id):
    try:
        cart = Cart.objects.get(id=cart_id)
        if cart.quantity == 1:
            pass
        else:
            cart.quantity -=1
            cart.save()
        return redirect(reverse('reastaurent:cart'))
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')

@login_required(login_url='user:login')
def increment_quantity(request, cart_id):
    try:
        cart = Cart.objects.get(id=cart_id)
        cart.quantity +=1
        cart.save()
        return redirect(reverse('reastaurent:cart'))
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')

@login_required(login_url='user:login')
def delete_cart(request):
    try:
        id = request.GET.get('id')
        cart = Cart.objects.get(id=id)
        cart.delete()
        return redirect(reverse('reastaurent:cart'))
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')


@login_required(login_url='user:login')
def delete_all_cart(request):
    try:
        carts = request.user.all_cart_food.all()
        for cart in carts:
            cart.delete()
        return redirect(reverse('reastaurent:restaurant_all'))
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')


def food(request,id):
    try:
        food = Food.objects.get(id=id)
        return render(request, 'food.html',context={"food":food})
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')

def view_all_food(request):
    try:
        foods = Food.objects.all().order_by('id')
        paginator = Paginator(foods, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request,'foods.html',context={"page_obj":page_obj})
    except Exception as ex:
        logging.warning(ex)
        return render(request,'error.html')

@login_required
def shipping(request):
    carts = request.user.all_cart_food.all()
    subtotal=0
    resadd = carts[0].restaurant.address
    coords_1 = None
    coords_2 = None
    if resadd.latitude == None or resadd.longitude == None:
        city = resadd.city
        state = resadd.state
        geolocator = Nominatim(user_agent="kundan")
        location = geolocator.geocode(city+' '+state)
        resadd.latitude = location.latitude
        resadd.longitude = location.longitude
        resadd.save()
        coords_1 = (location.latitude, location.longitude)
    else:
        coords_1 = (resadd.latitude, resadd.longitude)


    if request.user.address.latitude == None or request.user.address.longitude == None:
        city = request.user.address.city
        state = request.user.address.state
        ulocation = geolocator.geocode(city+' '+state)
        request.user.address.latitude = ulocation.latitude
        request.user.address.longitude = ulocation.longitude
        request.user.address.save()
        coords_2 = (ulocation.latitude, ulocation.longitude)
    else:
        coords_2 = (request.user.address.latitude, request.user.address.longitude)

    distance = geopy.distance.geodesic(coords_1, coords_2).km
    for cart in carts:
        subtotal += cart.quantity * cart.food.price


    shipping=int(distance * 50)
    total = subtotal+shipping
    if request.method == 'POST':
        data = request.POST.get('payment')
        order = Order(price = total,user=request.user,payment=data)
        order.save()
        carts = request.user.all_cart_food.all()
        for cart in carts:
            cart.delete()
        return HttpResponse('success')
    return render(request,'shipping.html',context={'subtotal':subtotal,'shipping':shipping,'total':total})


def search(request):
    item = []
    if request.method == 'POST':
        data = request.POST.get('search').lower()
        restaurants = Restaurant.objects.filter(name__icontains=data)
        foods = Food.objects.filter(name__icontains=data)

        for res in restaurants:
            item.append(['rastaurant',res])
        
        for food in foods:
            item.append(['food',food])
    return render(request,'search_result.html',context={"page_obj":item})

reastaurant/templates/cart.html
{% extends 'base.html' %}
    {% block content %}

    <div class="item">
        <section class="h-100" style="background-color: #eee;">
            <div class="container h-100 py-5">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-10">
          
                  <div class="d-flex justify-content-between align-items-center mb-4">
                    <h3 class="fw-normal mb-0 text-black">Your Order</h3>
                    <div>
                      <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!" class="text-body">price <i
                            class="fas fa-angle-down mt-1"></i></a></p>
                    </div>
                  </div>
          
                  {% for cart in carts  %}
                  <div class="card rounded-3 mb-4">
                    <div class="card-body p-4">
                      <div class="row d-flex justify-content-between align-items-center">
                        <div class="col-md-2 col-lg-2 col-xl-2">
                          <img
                            src="{{cart.food.image.all.0.image.url}}"
                            class="img-fluid rounded-3" alt="{{cart.food.name}}">
                        </div>
                        <div class="col-md-3 col-lg-3 col-xl-3">
                          <p class="lead fw-normal mb-2">{{cart.food.name}}</p>
                        </div>

                        <div class="col-md-3 col-lg-3 col-xl-2 d-flex">

                          <button class="btn btn-link px-2"
                            onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                            <a href="{% url 'reastaurent:decrement_quantity' cart.id %}">
                            <i class="fas fa-minus"></i>
                            </a>
                          </button>

                          <input id="formValue" min="0" name="quantity" value="{{cart.quantity}}" type="number"
                            class="form-control form-control-sm" />

                          <button class="btn btn-link px-2"
                            onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                            <a href="{% url 'reastaurent:increment_quantity' cart.id %}"><i class="fas fa-plus"></i></a>
                          </button>

                        </div>
                        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                          <h5 class="mb-0"><i class="fa fa-inr" aria-hidden="true"></i> {% widthratio cart.quantity 1 cart.food.price %}</h5>
                        </div>

                        <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                          <button type="button" onclick="checkUser({{cart.id}})" class="text-danger btn"><i class="fas fa-trash fa-lg"></i></button>
                        </div>
                      </div>
                    </div>
                  </div>

                  {% endfor %}

                  <div class="card mb-4">
                    <div class="card-body p-4 d-flex flex-row">
                      <div class="form-outline flex-fill">
                        <h4>Total Price:</h4>
                      </div>
                     
                      <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                        <h5 class="mb-0"> <i class="fa fa-inr" aria-hidden="true"></i>{{total_price}}</h5>
                      </div>
                    </div>
                  </div>
                  <div class="card mb-4">
                    <div class="card-body p-4 d-flex flex-row">
                      <div class="form-outline flex-fill">
                        <input type="text" id="form1" class="form-control form-control-lg" />
                        <label class="form-label" for="form1">Discound code</label>
                      </div>
                      <button type="button" class="btn btn-outline-warning btn-lg ms-3" style="height:48px;">Apply</button>
                    </div>
                  </div>
          
                  <div class="card">
                    <div class="card-body">
                      <a href="{% url 'reastaurent:shipping' %}"><button type="button" class="btn btn-warning btn-block btn-lg">Complete Order</button></a>
                      
                    </div>
                  </div>
          
                </div>
              </div>
            </div>
          </section>
    </div>    
    {% endblock content %}



    {% block javascript %}
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
      <script type="text/javascript">
          {% if cart_is_full %}
          function solve(){
            
            swal({
              title: "Previous Order is pending!!!",
              text: "Add this food, will remove all the food inside cart!!",
              buttons: true,
              dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                window.location = '{% url 'reastaurent:delete_all_cart' %}'
              }
            });
        }
        solve()
          {% endif %}

        function checkUser(id){
          swal({
            title: "Are you sure?",
            text: "want to delete item !!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              window.location = '{% url 'reastaurent:delete_cart'%}'+'?id='+id;
            }
          });
        }
      </script>

    {% endblock javascript %}

reastaurant/templates/food.html
{% extends 'base.html' %}

{% block content %}
<div class="slidebar">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-50" src="{{food.image.all.0.image.url}}" alt="First slide">
      </div>
    </div>
  </div>
  
      
  <div class="resto-info">
      <h2>{{food.name}}</h2>
      <h3><i class="fa fa-inr" aria-hidden="true"> {{food.price}}</i></h3>
  </div>
  <hr>
  
          
  <div class="deliciousfood">
      <h3>This food is available on these Restaurant</h3>
      <div class="scrollmenu">
        {% for restaurant in food.restaurants_foods.all  %}
        <div class="card">
          <a href="{% url 'reastaurent:restaurant' restaurant.id %}">
            <img class="card-im card-img-top" src="{{restaurant.image.all.0.image.url}}" alt="Card image cap">
          </a>
          <div class="card-body">
            <h5 class="card-title"> {{restaurant.name}} <span> <a class="btn btn-secondary" style="margin-right:40px;" href="{% url 'reastaurent:add_to_cart' restaurant.id food.id %}">Order from here</a></span></h5>
            <p class="card-text">{{restaurant.address.area}}, {{restaurant.address.city}}</p>
          </div>
        </div>
        {% endfor %} 
      </div>
  </div>
  
  {% endblock content %}
  
  

reastaurant/templates/restaurant.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    
    <!-- Reastoreant -->

<div class="slidebar">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-50" src="{{restaurant.image.all.0.image.url}}" alt="First slide">
    </div>
  </div>
</div>

    
<div class="resto-info">
    <h2>{{restaurant.name}}</h2>
    <h3><span>{{restaurant.rating}}  <i class="fa-solid fa-star"></i></span> </h3>
    <p class="restro-txt">Address :{{restaurant.address.area}},{{restaurant.address.city}},{{restaurant.address.state}},{{restaurant.address.country}}<br/>PinCode :{{restaurant.address.pincode}}<br/>Phone :{{restaurant.phone}}</p>
</div>
<hr>

        
<div class="deliciousfood">
    <h3>Menu</h3>
    <div class="scrollmenu">

      {% for food in restaurant.food.all  %}
      
      <div class="card">
        <a href="">
          <img class="card-im card-img-top" src="{{food.image.all.0.image.url}}" alt="Card image cap">
        </a>
        <div class="card-body">
          <h5 class="card-title"> {{food.name}} <span> <a class="btn btn-secondary" style="margin-right:40px;" href="{% url 'reastaurent:add_to_cart' restaurant.id food.id %}">Add to Cart</a> <i class="fa-solid fa-indian-rupee-sign"></i> {{food.price}}  </span></h5>
        </div>
      </div>
      {% endfor %} 
    </div>
</div>

{% endblock content %}

reastaurant/templates/shipping.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/profile_update.css' %}">
{% endblock extra_css %}

{% block content %}

<div class="container">
    <div class="row gutters">
        
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
        
    <div class="card h-100">
        <div class="card-body">
            <h3>Complete Shipping Address</h3>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mb-2 text-primary">Personal Details</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" class="form-control" id="first_name" placeholder="Enter First name" value="{{request.user.first_name}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" class="form-control" id="last_name" placeholder="Enter Last name" value="{{request.user.last_name}}">
                    </div>
                </div>
                
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" class="form-control" id="phone" placeholder="Enter phone number" value="{{request.user.phone}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="eMail">Email</label>
                        <input type="email"  class="form-control" id="eMail" placeholder="Enter email ID" value="{{request.user.email}}" disabled>
                    </div>
                </div>
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mt-3 mb-2 text-primary">Address</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="Street">Area</label>
                        <input type="name" class="form-control" id="area" placeholder="Enter Area" value="{{request.user.address.area}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="ciTy">City</label>
                        <input type="name" class="form-control" id="ciTy" placeholder="Enter City" value="{{request.user.address.city}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="sTate">State</label>
                        <input type="text" class="form-control" id="sTate" placeholder="Enter State" value="{{request.user.address.state}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="zIp">Zip Code</label>
                        <input type="text" class="form-control" id="zIp" placeholder="Zip Code" value="{{request.user.address.pincode}}">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="country">Country</label>
                        <input type="text" class="form-control" id="country" placeholder="Enter Country" value="{{request.user.address.country}}">
                    </div>
                </div>
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                        <input type="button" id="submit" name="submit" class="btn btn-primary" onclick="update_profile()" value="Save" >
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
            <div class="card-body">

                <div class="row gutters">
                    <div class="col-12">
                        <h6 class="mb-2 text-primary">Payment Details</h6>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <h6>Subtotal</h6>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <h6><i class="fa fa-inr" aria-hidden="true"> {{subtotal}}</i></h6>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <h6>Shiping</h6>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <h6><i class="fa fa-inr" aria-hidden="true"> {{shipping}}</i></h6>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <h6>Total</h6>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <h6><i class="fa fa-inr" aria-hidden="true"></i> {{total}}</h6>
                        </div>
                    </div>
                </div>

                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                            <label class="form-check-label" for="flexCheckChecked">
                              COD (cash on delivery)
                            </label>
                          </div>
                        <div class="text">
                            <input type="button" id="submit" name="submit" class="btn btn-primary" onclick="orderplaced()" value="Checkout" >
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    </div>

    {% endblock content %}

    {% block javascript %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        <script type="text/javascript">
            let first_name,last_name,phone,area,city,state,pincode,country
            function update_profile(){
                first_name=$("#first_name").val();
                last_name=$("#last_name").val();
                phone = $("#phone").val();
                area = $("#area").val();
                city = $("#ciTy").val();
                state = $("#sTate").val();
                country = $("#country").val();
                pincode = $("#zIp").val();
                let data = new FormData();
                data.append("csrfmiddlewaretoken", "{{csrf_token}}");
                data.append("first_name",first_name);
                data.append("last_name",last_name);
                data.append("phone",phone);
                data.append("area",area);
                data.append("city",city);
                data.append("state",state);
                data.append("country",country);
                data.append("pincode",pincode);
                $.ajax({
                    type: 'POST',
                    url: {% url 'user:profile_update' %},
                    success: function(e) { window.location='{% url 'reastaurent:shipping' %}' },
                    processData:false,
                    contentType:false,
                    data:data
                });
            }

            function orderplaced(){
                let check=$('#flexCheckChecked').is(":checked")
                let payment
                let data = new FormData();
                data.append("csrfmiddlewaretoken", "{{csrf_token}}");
                if(check){
                    payment = 'cash on delivery';
                }else{
                    payment = 'online payment';
                }
                data.append('payment',payment)

                $.ajax({
                    type: 'POST',
                    url:'{% url 'reastaurent:shipping' %}',
                    data:data,
                    success:function(e){
                        let text
                        if(check){
                            text='Be Ready with cash!!'
                        }else{
                            text='Your payment Received!!'
                        }
                        swal({
                            title: "Thanks for order!!",
                            text: text,
                            icon: "success",
                        }).then((e)=>{
                            window.location= '{% url 'user:home' %}'
                        });
                    },
                    processData:false,
                    contentType:false,
                });
            }
        </script>
    {% endblock javascript %}